---
- name: Converge
  hosts: all
  become: false
  tasks:
    - name: Ensure www-data user exists
      ansible.builtin.user:
        name: www-data
        shell: /sbin/nologin
        
    - name: Ensure web root exists
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Include web role
      include_role:
        name: web
