---
- name: Verify role behavior
  hosts: all
  gather_facts: false

  tasks:
    - name: Verify Nginx is installed
      ansible.builtin.assert:
        that:
          - "'nginx' in ansible_facts.packages"
